- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
+ incerase nodeStartupTimeout to 5min
+ add alias for kubectl
> Increase healthcheck startup timeout

- pkg/cluster/internal/providers/docker/stratio/Dockerfile
Upgrade version clusterctl & clusterawsadm to v1.3.2 & v2.0.2 respect…
> Upgrade version clusterctl & clusterawsadm

- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/eks.go
* Update AWSIAMConfiguration apiversion
* Update MachineHealthCheck apiVersion
> Upgrade apiversion

- pkg/cluster/internal/create/actions/cluster/cluster.go
- pkg/cluster/internal/create/actions/createworker/utils.go
> Add Copyrigth

- pkg/cluster/internal/create/actions/createworker/createworker.go
omit IAM cloudformation stack when  is specified
> [EOS-11007] No ejecutar el paso de "IAM security" si se indica --avoid-creation

- DEPENDENCIES
- docs/cloud-provisioner/Versiones.md
- pkg/apis/config/defaults/image.go
- pkg/cluster/internal/create/actions/cluster/templates/aws.eks.tmpl
- pkg/cluster/internal/create/actions/createworker/files/gcp-compute-persistent-disk-csi-driver.yaml
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/create/actions/createworker/templates/calico-helm-values.tmpl
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
Actualización de Versiones
Ver Fichero docs/cloud-provisioner/Versiones.md
> [EOS-11162] Actualizar versiones

- pkg/cluster/internal/create/actions/cluster/cluster.go
- pkg/cluster/internal/create/actions/createworker/utils.go
https://github.com/Stratio/keos-installer/blob/43ae7aa719fcfaf2a8fd9779f4b2b4864271432d/ansible/inventory/group_vars/all/01-aws.yml#L5
> fix: align account param with keos

- pkg/cluster/internal/create/actions/cluster/cluster.go
- pkg/cluster/internal/create/actions/createworker/keosinstaller.go
backporting --> https://github.com/Stratio/kind/pull/116
`keos.domain` in `keos.yaml` must take always the following value whatever the provider is configured: `cluster.local`
> fix: set fixed value of

- pkg/cluster/internal/create/actions/createworker/keosinstaller.go
- pkg/commons/cluster.go
- pkg/commons/utils.go
- Add azure resource_group to keos.yaml
- Remove resource_group from secrets.yml
> Fix Azure keos integration

- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/operations.adoc
Se eliminan índices no necesarios para Antora.
> [0.1] DOC - Índices eliminados

- pkg/cmd/kind/version/version.go
> [Cloud-83] Actualizar la version del provisioner

- CHANGELOG.md
- DEPENDENCIES
- pkg/cluster/internal/create/actions/createworker/azure.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
Bump several capx versions in ordert to support k8s 1.28
> bump capx versions

- Jenkinsfile
> Doc jenkinsfiledoc

- go.mod
- pkg/cluster/internal/create/actions/createworker/aws.go
- pkg/cluster/internal/create/actions/createworker/azure.go
- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/validate/aws.go
- pkg/cluster/internal/validate/azure.go
- pkg/cluster/internal/validate/common.go
- pkg/cluster/internal/validate/gcp.go
- pkg/commons/cluster.go
* Add Google Container Registry (aka gcr) support for gcp managed and unmanaged clusters
* Add Google Artifact Registry (aka gar) support for gcp managed and unmanaged clusters
* Enable GKE and Machine Pools support to capg provider in gcp managed clusters
* Refactor docker registries credentials logic
> [CLOUD-109] Integrar GKE como nuevo provider

- pkg/cluster/internal/validate/aws.go
- pkg/cluster/internal/validate/azure.go
- pkg/cluster/internal/validate/gcp.go
**_non-existing region=eu-west-11_**
Error message:
```
ERROR: failed to validate cluster: spec.region: eu-west-11 region does not exist
```
**_non-existing region=westeurope1_**
Error message:
```
ERROR: failed to validate cluster: spec.region: westeurope1 region does not exist
```
**_Non-existing region=1europe-west4_**
Error message:
```
ERROR: failed to validate cluster: spec.region: 1europe-west4 region does not exist
```
> chore: validate region exists

- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cmd/kind/version/version.go
- Correct phase title `Installing cluster-autoscaler in workload cluster`
> fix: Fix helm repo authorization

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/provider.go
> [FIX] fix pdb deployment

- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/validate/aws.go
- pkg/cluster/internal/validate/azure.go
- pkg/cluster/internal/validate/gcp.go
- pkg/commons/cluster.go
Related to -> https://github.com/Stratio/cluster-operator/pull/150
> [CLOUD-148] Soportar vpc_cidr sin especificar vpc_id ni subnets

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/aws.go
- pkg/cluster/internal/create/actions/createworker/azure.go
- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/overridevars.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/commons/cluster.go
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Related to --> https://github.com/Stratio/cluster-operator/pull/182
> [CLOUD-213] Hacer opcional el despliegue del aws-loadbalancer-controller en el ClusterConfig (default: no instalar)

- Jenkinsfile
- bin/deploy.sh
- bin/package.sh
- docs/descriptor/keoscluster_v1beta1_template.yaml
Incluir la plantilla de cluster.yaml al flujo de CICD.
> 👷FLOW-3090 - Add cluster template to CICD workflow

- scripts/upgrade-provisioner.py
Support OCI for helm URL in upgrade
N/A
> [FIX][Upgrade] Support OCI for helm URL in upgrade

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
Esta PR arregla un error en un tag de la página de arquitectura y actualiza la versión en inglés de dicha página, que se ha detectado que estaba incompleta.
> [branch-0.2] Typo on architecture page and EN version updated

- pkg/cluster/internal/create/actions/createworker/files/aws/public-ingress-nginx.yaml
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Fix required annotations for AWS load balancer controller when needed
- https://github.com/Stratio/kind/pull/531
> [EKS] Add required permissions for AWS LB controller 

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> [branch-0.3] EN and ES version aligned

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> branch-0.4] EN and ES version aligned

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> [master] EN and ES versions aligned

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
> [branch-0.5] EN and ES versions aligned (#552)

- CHANGELOG.md
- scripts/upgrade-provisioner.py
Upgrade script
- https://stratio.atlassian.net/browse/CLOUD-281
> [CLOUD-281] upgrade script 0.4.x to 0.5.0

- stratio-docs/en/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/assets/attachments/stratio-gcp-permissions.list
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Update GCP Permissions
Re-write EKS permissions reference - installation.adoc
N/A
> Stratio docs update

- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Modify version 1.26 to 1.28 on installation doc
N/A
> [DOC] Modify version 1.26 to 1.28

- docs/cloud-provisioner/Versiones.md
> [DOC] Fix table view on pause version

- CHANGELOG.md
Bump new version 0.17.0-0.5.1
N/A
> [Chore] Bump new version 0.17.0-0.5.1

- CHANGELOG.md
- scripts/upgrade-provisioner.py
improve upgrade script getting keos cluster
N/A
> [Chore] Improve upgrade script

- CHANGELOG.md
- pkg/cmd/kind/version/version.go
> [Chore] Revert changes 0.5.1

- pkg/cmd/kind/version/version.go
[Chore] Prepare release 0.5.1
N/A
> [Chore] Prepare release 0.5.1

- stratio-docs/en/modules/operations-manual/pages/image-builder/azure-image-builder.adoc
- stratio-docs/en/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
- stratio-docs/es/modules/operations-manual/pages/image-builder/azure-image-builder.adoc
- stratio-docs/es/modules/operations-manual/pages/image-builder/gcp-image-builder.adoc
Fix bad AWS reference on Image builder GCP and Azure files
N/A
> [DOC] Fix AWS error reference on Azure and GCP files

- CHANGELOG.md
- pkg/cmd/kind/version/version.go
- scripts/upgrade-provisioner.py
[Chore] Update versions in upgrade script
N/A
> [Chore] Update versions in upgrade script

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/aws.go
- pkg/cluster/internal/create/actions/createworker/azure.go
- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/commons/utils.go
Improve ExecuteCommand:
- Add new webhook message error
- Add a Regex: Integrate a new regular expression (regex) for improved pattern matching and validation.
- Parametrize Retries: Introduce parameters for retry attempts to increase the flexibility and robustness of the command execution process.
N/A
> [Chore] Improve ExecuteCommand

- CHANGELOG.md
- scripts/upgrade-provisioner.py
Enabled min_size to be set to zero during upgrade
https://stratio.atlassian.net/browse/CLOUD-274
> [FIX][Upgrade] Support min_size to 0 in upgrade

- pkg/cluster/internal/create/actions/createworker/keosinstaller.go
- pkg/commons/cluster.go
Delete keos.version and deploy_tigera_operator reference
- https://github.com/Stratio/kind/pull/578
> Delete keos.version and deploy_tigera_operator references

- docs/descriptor/keoscluster_v1beta1.yaml
- docs/descriptor/keoscluster_v1beta1_template.yaml
> Add keoscluster template for CICD

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cmd/kind/version/version.go
- scripts/upgrade-provisioner.py
Preparing for prerrelease 0.5.3
> Preparing prerrelease 0.5.3

- pkg/cluster/internal/validate/azure.go
> [PLT-620] [Azure] Soportar imágenes públicas

- stratio-docs/es/modules/ROOT/assets/attachments/stratio-gke-permissions.list
Update Permissions  list
- None
> [DOC] Add compute.instanceGroupManagers.get to stratio-gke-permissions.list

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
> docs fixes

- CHANGELOG.md
- DEPENDENCIES
- bin/images/commons/imagenes-calico.txt
- bin/images/gcp/imagenes-csi-node.txt
- docs/cloud-provisioner/Versiones.md
- pkg/cluster/internal/create/actions/createworker/aws.go
- pkg/cluster/internal/create/actions/createworker/azure.go
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/templates/common/30/tigera-operator-helm-values.tmpl
- stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-eks-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/aws-vms-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-vms-images.adoc
> [PLT-817] Bump Tigera Operator version to v3.28.2

- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/create/actions/kubeadminit/init.go
- pkg/cluster/internal/create/create.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
- pkg/commons/cluster.go
GKE  Private cluster
PR: https://github.com/Stratio/cluster-operator/pull/227
PR: https://github.com/Stratio/cluster-api-provider-gcp/pull/15
> [PLT-806] GKE nodos privados

- pkg/cluster/internal/create/actions/createworker/gcp.go
> [Fix gcp version]

- pkg/cluster/internal/create/actions/createworker/gcp.go
> [Fix] gcp pre-release version

- CHANGELOG.md
Updated changelog with changes PLT-911 contained in PR https://github.com/Stratio/kind/pull/611/files
https://github.com/Stratio/kind/pull/611/files
> Added PLT-911 to changelog

- pkg/cluster/internal/create/actions/createworker/provider.go
Add kubebuilkder to private kube-rbac-proxy:v0.13.1
None
> [PLT-923] Add path /kubebuilder for kube-rbac-proxy image url

- pkg/cluster/internal/create/actions/createworker/aws.go
- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/create/actions/createworker/files/common/calico-metrics.yaml
- pkg/cluster/internal/create/actions/createworker/keosinstaller.go
- pkg/cluster/internal/create/actions/createworker/provider.go
- pkg/cluster/internal/create/actions/createworker/templates/common/30/tigera-operator-helm-values.tmpl
- pkg/commons/cluster.go
Fixed Bugs:
https://stratio.atlassian.net/browse/PLT-915
No se descargaba el tigera-operator en instalaciones de EKS y por otro lado, el namespace en el que se espera que tigera-operator se instale ha cambiado, ha pasado de calico-system a tigera-operator
> [PLT-915][PLT-891] Fixes to install with EKS

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/commons/cluster.go
Manage Google Cloud Managed Service for Prometheus
https://github.com/Stratio/cluster-operator/pull/236
https://github.com/Stratio/cluster-api-provider-gcp/pull/26
> [PLT-965] [GKE] Deshabilitar monitorización/logs gestionada

- pkg/cluster/internal/create/actions/createworker/gcp.go
> [Update cluster api provider gcp]

- pkg/cluster/internal/providers/docker/stratio/Dockerfile
> Update capg-version dependencies

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
- pkg/commons/cluster.go
* Add monitoring and logging configuration
* Add changelog
* Update cluster-api-provider-gcp pre-release
> [PLT-965] [GKE] Deshabilitar monitorización/logs gestionada (#620)

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
Fix final reference for cluster-api-provider-gcp image
> Fix provider gcp image

- pkg/cluster/internal/create/actions/createworker/files/gcp/allow-egress-imds_gnetpol.yaml
Solucionado problema de GlobalNetworkPolicy, allow-traffic-to-gcp-imds-capg, para poder acceder a IMDS.
> Fixed GNP in GKE

- pkg/cluster/internal/create/actions/createworker/aws.go
Fix aws-load-balancer-controller deployment
N/A
- JIRA Link: https://stratio.atlassian.net/browse/PLT-1178
> [PLT-1178] fix aws-load-balancer-controller

- CHANGELOG.md
> Fix PLT-964

- CHANGELOG.md
- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/validate/gcp.go
- pkg/commons/cluster.go
Soportar CMEK y SA para los nodepools
N/A
JIRA: https://stratio.atlassian.net/browse/PLT-1246
> [PLT-1246] [GKE] Soportar CMEK para los discos root de los workers

- pkg/cluster/internal/providers/docker/stratio/Dockerfile
> Fix assets

- pkg/cluster/internal/create/actions/createworker/gcp.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
> Update capg version

- docs/gcp/GKE Bastion.md
- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Update changes from 0.5 to master
> [PLT-719] Doc 0.5 to master

- docs/gcp/GKE Bastion.md
- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Update changes from 0.5 to 0.6
> [PLT-719] Doc 0.5 to 0.6

- stratio-docs/en/modules/ROOT/pages/installation.adoc
Fix:
- Column view
- json format
> [PLT-719] Doc Fixes English version

- .gitignore
- docs/gcp/GKE Bastion.md
Add more information to bastion doc
> [Doc] Update Bastion documentation

- stratio-docs/en/modules/ROOT/pages/installation.adoc
Fix Column on stratio-docs/en/modules/ROOT/pages/installation.adoc
N/A
> [Doc] fix Columns 

- stratio-docs/en/modules/ROOT/pages/installation.adoc
Fix Column on stratio-docs/en/modules/ROOT/pages/installation.adoc
N/A
> [Doc] fix Columns

- pkg/cluster/internal/validate/gcp.go
> [PLT-1332] Fix ip_alloc

- pkg/cluster/internal/validate/gcp.go
Fix and improve some GKE validations after merge
N/A
> [PLT-1332] [GKE] Fix and improve validations

- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Esta PR arregla algunos errores detectados al desplegar la documentación en Antora, relativos a la renderización del contenido y erratas tipográficas. Gracias.
> [branch-0.17.0-0.5] Several fixes on the installation page

- stratio-docs/en/modules/ROOT/assets/attachments/stratio-gke-permissions.list
- stratio-docs/es/modules/ROOT/assets/attachments/stratio-gke-permissions.list
Fix autoCP -> autoCP-857c9aaedfcb3a7d2fdaf5439d7add98eb508cdb/master
Add  missing files by auto-cherry
https://github.com/Stratio/kind/pull/666
> [FIX] Cherry pick autoCP(master)

- stratio-docs/en/modules/ROOT/assets/attachments/stratio-gke-permissions.list
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/assets/attachments/stratio-gke-permissions.list
- stratio-docs/es/modules/ROOT/pages/installation.adoc
AUTO cherry-picking some fixes (#665)
> [AUTO cherry-pick branch-0.17.0-0.5->master] some fixes (#66

- DEPENDENCIES
- Jenkinsfile
- bin/images/gcp/imagenes-capg.txt
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
- pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
- pkg/commons/cluster.go
- stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
> Updated CAPG version

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/en/modules/ROOT/pages/quick-start-guide.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
AUTO cherry-picking [PLT-1165] Documentar GKE 0.6.x (#672)
* Update GKE doc
* Update stratio-docs/es/modules/ROOT/pages/installation.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/es/modules/ROOT/pages/quick-start-guide.adoc
Co-authored-by: Teresa Pérez Senso …
> [AUTO cherry-pick branch-0.17.0-0.6->master] [PLT-1165] Docu

- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
- stratio-docs/es/modules/ROOT/pages/architecture.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation.adoc
> [branch-0.17.0-0.4] Errores en tablas

- pkg/cluster/internal/validate/gcp.go
- pkg/commons/cluster.go
* Added extended channel suport for GKE
* Added extended channel by default
* Modified channel options
---------
> Feature/plt 1496 add support extended channel (#687)

- pkg/cluster/internal/create/actions/createworker/createworker.go
- pkg/cluster/internal/providers/docker/stratio/Dockerfile
- Añadimos el clide aws al Dockerfile para poder obtener las subnetes con ciertos tags
- Añadimos las eniconfig que el provider no genera para que el vpc-cni (aws-node) puede funcionar correctamente
N/A
> [PLT-1716] [EKS] Desplegar utilizando únicamente el parámetro pods_cir en networks falla

- DEPENDENCIES
- bin/images/gcp/imagenes-capg.txt
Update cluster-api-gcp-controller version references
N/A
> Update cluster-api-gcp-controller version references

- CHANGELOG.md
[CICD] Autocalculate CHANGELOG based on git history for master
> [CICD] Autocalculate CHANGELOG for master

- CHANGELOG.md
[CICD] Autocalculate CHANGELOG based on git history for branch-0.17.0-0.7
> [CICD] Autocalculate CHANGELOG for branch-0.17.0-0.7

- CHANGELOG.md
- pkg/cluster/internal/validate/aws.go
Make region describe step dynamic based on descriptor region
N/A
> [PLT-1887] Dynamic region describe

- pkg/cluster/internal/create/actions/createworker/templates/aws/30/aws-load-balancer-controller-helm-values.tmpl
- pkg/cluster/internal/create/actions/createworker/templates/aws/31/aws-load-balancer-controller-helm-values.tmpl
- pkg/cluster/internal/create/actions/createworker/templates/aws/32/aws-load-balancer-controller-helm-values.tmpl
- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
- Fix aws-load-balancer-controller:
> Modify helm values to add role annotation
> Add missed permission to procedure doc.
N/A
> [PLT-1849] Error 403 sts:AssumeRoleWithWebIdentity en ingress-nginx-controller

- stratio-docs/en/modules/ROOT/pages/installation.adoc
- stratio-docs/es/modules/ROOT/pages/installation.adoc
Add final step on aws-load-balancer deployment
N/A
> [DOC] [EKS] Update aws-load-balancer documentation

- pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
- scripts/requirements.txt
- scripts/upgrade-provisioner.py
- stratio-docs/en/modules/operations-manual/pages/upgrade.adoc
- stratio-docs/es/modules/operations-manual/pages/upgrade.adoc
> [PLT-1652] Allow skipping kubernetes intermediate version during upgrade

- CHANGELOG.md
> [PLT-1849] Fix aws-load-balancer-controller annotation

- stratio-docs/en/modules/ROOT/nav.adoc
- stratio-docs/en/modules/ROOT/pages/architecture.adoc
- stratio-docs/en/modules/operations-manual/pages/credentials.adoc
- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/ROOT/nav.adoc
- stratio-docs/es/modules/operations-manual/pages/credentials.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
* [PLT-1823] Improve Clouds credentials management documentation
* [PLT-1823] Improve Clouds credentials management documentation
* [PLT-1823] Improve Clouds credentials management documentation
* [PLT-1823] Improve Clouds credentials management documentation
* Apply suggestions from code review
* Update credentials.adoc
* [PLT-1823] Improve Clouds credentials management documentation
* [PLT-1823] Improve Clouds credentials management documentation
* Update of installation.adoc file in EN version
* Apply suggestions from code review
---------
[PLT-1823]: https://stratio.atlassian.net/browse/PLT-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
> [PLT-1823] Improve Clouds credentials management documentation (#707)

- CHANGELOG.md
- stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
> [PLT-1922] Rename reference to aws-load-balancer-controller

- CHANGELOG.md
- stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/es/modules/operations-manual/pages/api-reference.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
AUTO cherry-picking [PLT-1922] Rename reference to aws-load-balancer-controller (#741)
* [PLT-1922] Fix reference aws-load-balancer-controller
* [PLT-1922] Fix reference aws-load-balancer-controller
[PLT-1922]: https://stratio.atlassian.net/browse/PLT-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLT-1922]: https://stratio.atlassian.net/browse/PLT-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PLT-1922]: https://stratio.atlassian.net/browse/PLT-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AUTO cherry-pick branch-0.17.0-0.6->branch-0.17.0-0.7] [PLT

- stratio-docs/en/antora.yml
- stratio-docs/es/antora.yml
AUTO cherry-picking antora.yaml version update (#753)
> [AUTO cherry-pick branch-0.17.0-0.7->master] antora.yaml ver

- stratio-docs/es/modules/ROOT/pages/installation.adoc
> [branch-0.17.0-0.5] DOC - little fixes

- pkg/cluster/internal/create/actions/createworker/azure.go
> [PLT-2052] Fix Azure charts versions references

- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
> [branch-0.17.0-0.7] General errors fixed

- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/en/modules/operations-manual/pages/offline-installation.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
AUTO cherry-picking General error fixed (#773)
> [AUTO cherry-pick branch-0.17.0-0.7->master] General error f

- CHANGELOG.md
- scripts/upgrade-provisioner.py
> [PLT-2131] Improve workers checks during cloud-provisioner upgrade to avoid timeouts

- CHANGELOG.md
- scripts/upgrade-provisioner.py
Revisar la necesidad de actualizar los cri_volumes ene l cluster
N/A
> [PLT-2132] Remove cri volumes management from upgrade

- stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
> [branch-0.17.0-0.7] Error in table

- stratio-docs/en/modules/operations-manual/pages/api-reference.adoc
> [master] Error in table (#790)

- pkg/cluster/internal/validate/aws.go
- pkg/cluster/internal/validate/utils.go
- pkg/commons/cluster.go
- pkg/commons/utils.go
Fix empty role_arn on secrets.yml
N/A
> [PLT-2335] No levanta docker keos-installer con parámetro role_arn:'false' en secrets.yaml

- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
AUTO cherry-picking [UPDATE DOC] Update assume role documentation (#801)
* Update sts documentation
* Update stratio-docs/es/modules/operations-manual/pages/installation.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/en/modules/operations-manual/pages/installation.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
---------
Co-authored-by: Teresa Pérez Senso …
> [AUTO cherry-pick branch-0.17.0-0.7->master] [UPDATE DOC] Up

- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
> [PLT-2379] Fix namespace reference

- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
AUTO cherry-picking [PLT-2379] Fix namespace reference (#804)
* [PLT-2379] Fix namespace reference
* [PLT-2379] Fix namespace reference
* [PLT-2379] Update text: Edit the "aws-auth" configmap adding the "iam_role".
* Update stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Apply suggestions from code review
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
---------
Co-authored-by: Unai Arríen <unaittxu@gmail.com>
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
[PLT-2379]: https://stratio.atlassian.net/browse/PLT-2379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
> [AUTO cherry-pick branch-0.17.0-0.7->master] [PLT-2379] Fix 

- CHANGELOG.md
- pkg/cluster/internal/providers/docker/images.go
> [PLT-2389] Fix  image reference during cluster creation

- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
We are adding a key note refering to modify user credentials and role_arn in capa and keoscluster.
> [Update] Assume role documentation

- stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
- stratio-docs/es/modules/operations-manual/pages/operations-manual.adoc
AUTO cherry-picking [Update] Assume role documentation (#810)
* Update role arn docuemntation
* Update role arn docuemntation
* Update role arn docuemntation
* Update stratio-docs/en/modules/operations-manual/pages/operations-manual.adoc
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
* Update role arn docuemntation
* Update operations-manual.adoc
---------
Co-authored-by: Teresa Pérez Senso <44154626+tperez-stratio@users.noreply.github.com>
> [AUTO cherry-pick branch-0.17.0-0.7->master] [Update] Assume

- stratio-docs/en/modules/operations-manual/pages/installation.adoc
- stratio-docs/es/modules/operations-manual/pages/installation.adoc
AUTO cherry-picking [GKE] Update doc (#813)
* Update doc with secure boot
* Update doc with secure boot
> [AUTO cherry-pick branch-0.17.0-0.7->master] [GKE] Update do

- CHANGELOG.md
- DEPENDENCIES
- docs/images/azure/imagenes-cloud-provider-azure.txt
- pkg/cluster/internal/create/actions/createworker/templates/azure/32/cloud-provider-azure-helm-values.tmpl
- stratio-docs/en/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
- stratio-docs/es/modules/operations-manual/pages/offline-installation/azure-vms-images.adoc
Bump azure-cloud-controller-manager and azure-cloud-node-manager to version 1.33.2
https://github.com/Stratio/kubernetes-universe/pull/3045
> [PLT-2646] Bump azure-cloud-controller-manager and azure-cloud-node-manager to version 1.33.2
