Stratio/kind

pkg/cluster/internal/providers/docker/provision.go

Al hacer el docker run usa la imagen (que contiene el sha):
'stratio-capi-image:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1'
en lugar de la imagen:
stratio-capi-image:v1.25.3

Fix image tag from sha to version

---

pkg/cluster/internal/create/actions/createworker/eksgen.go

so we can use bootstrap.cluster.x-k8s.io/v1beta2 and infrastructure.cluster.x-k8s.io/v1beta2

bump CAPA to v2.0.2

---

pkg/cluster/internal/create/actions/cluster/cluster.go
pkg/cluster/internal/create/actions/createworker/keosinstaller.go

- Add `dns.hosted_zones` parameters to `cluster.yaml`. Default value `true`
- Add `keos.dns.external_dns.enabled` to `keos.yaml` depending on value `dns.hosted_zones`. Default value `true`
- `deploy_tigera_operator` set to `true` when provider is `managed`

[EOS-10983] Make `external-dns` optional

---

pkg/cluster/internal/create/actions/cluster/cluster.go
pkg/cluster/internal/create/actions/createworker/keosinstaller.go

`keos.domain` always takes the value of `cluster.local`
if `spec.keos.domain` has a value in `cluster.yaml` `keos.domain` takes always that value in `keos.yaml`
if `spec.keos.domain` doesn't exist in `cluster.yaml` `keos.domain` will not exist in `keos.yaml` (by default in keos-installer it will take the default value of `$cluster_id.int`)

[EOS-11130] Handle keos domain parameter

---

go.mod
go.sum
pkg/cluster/internal/create/actions/createworker/templates/aws.eks.tmpl
pkg/cmd/kind/create/cluster/validation/eksvalidator.go
pkg/commons/cluster.go

[Managed (dynamic) VPC](https://cluster-api-aws.sigs.k8s.io/topics/eks/pod-networking.html#managed-dynamic-vpc)
Default configuration for CAPA is to manage the VPC and all the subnets for you dynamically. It will create and delete them along with your cluster. In this method all you need to do is set a SecondaryCidrBlock to one of the allowed two IPv4 CIDR blocks: 100.64.0.0/10 and 198.19.0.0/16. CAPA will automatically generate subnets and ENIConfigs for you and the VPC CNI will do the rest.
[Unmanaged (static) VPC](https://cluster-api-aws.sigs.k8s.io/topics/eks/pod-networking.html#unmanaged-static-vpc)
In an unmanaged VPC configuration CAPA will create no VPC or subnets and will instead assign the cluster pieces to the IDs you pass. In order to get ENIConfigs to generate you will need …

[EOS-11148] Refinar el uso de un CIDR (secundario) específico para Pods

---

pkg/cluster/internal/create/actions/createworker/keosinstaller.go

If `keos.flavour`  is not defined in `cluster.yaml`, `keos.flavour` will not be defined in `keos.yaml`
If `keos.flavour` is defined in `cluster.yaml`, `keos.flavour` will be defined in `keos.yaml` with same value

[EOS-11411] [ClusterAPI] Fix behaviour of keos flavour parameter

---

pkg/cluster/internal/create/actions/createworker/templates/gcp.tmpl

`.spec.worker_nodes[].name` containing `spec.cluster_id`  is not mandatory anymore.
Example:
```
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
spec:
cluster_id: xxxxxxxxxx
infra_provider: gcp
k8s_version: v1.24.10
region: europe-west4
docker_registries:
- url: eosregistry.azurecr.io/keos
auth_required: true
type: generic
keos_registry: true
keos:
domain: cluster.local
flavour: minimal
version: 0.8.0
calico:
pool: 10.1.0.0/16
control_plane:
managed: false
size: n2-standard-2
node_image: projects/clusterapi-369611/global/images/cluster-api-ubuntu-2204-v1-23-15-1679931010
root_volume:
size: 50
type: pd-ssd
worker_nodes:
- name: workers-1
quantity: 4
max_size: 8
min_size: 3
zone_distribution: balanced
size: n2-standard-2
node_image: …
```

[EOS-1144][GCP] Usar additionalNetworkTags para quitar dependencia de cluster_name en grupo de nodos

---

pkg/cluster/internal/create/actions/createworker/keosinstaller.go
pkg/commons/cluster.go

cluster.yaml
```
...
storageclass:
efs:
name: fs-015ea5e2ba5fe7fa5
id: fs-015ea5e2ba5fe7fa5
permissions: 640
...
```
keos.yaml
```
...
storage:
providers:
- csi-aws
config:
csi-aws:
efs:
- id: fs-015ea5e2ba5fe7fa5
name: support-efs-capi
permissions: "640"
...
```
Rotate keos.yaml each execution of cloud-provisioner

[EOS-11436] Configurar EFS en el descriptor (para renderizar el keos.yaml)

---

pkg/commons/cluster.go

forwarders is an array, not a single string

Fix forwarders check

---

CHANGELOG.md
pkg/cluster/internal/create/actions/createworker/aws.go
pkg/cluster/internal/create/actions/createworker/azure.go
pkg/cluster/internal/create/actions/createworker/createworker.go
pkg/cluster/internal/create/actions/createworker/files/common/coredns_pdb.yaml
pkg/cluster/internal/create/actions/createworker/files/gcp/gcp-compute-persistent-disk-csi-driver.yaml
pkg/cluster/internal/create/actions/createworker/gcp.go
pkg/cluster/internal/create/actions/createworker/provider.go
pkg/cluster/internal/create/actions/createworker/templates/common/calico-helm-values.tmpl

**AKS** ✅
kube-system    coredns    {"emptyDir":{},"name":"tmp"} 🆗
```bash
Pod Template:
Labels:           k8s-app=kube-dns
kubernetes.azure.com/managedby=aks
kubernetes.io/cluster-service=true
version=v20
Annotations:      cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: tmp
```
kube-system    metrics-server    {"emptyDir":{},"name":"tmp-dir"} 🆗
```bash
Pod Template:
Labels:           k8s-app=metrics-server
kubernetes.azure.com/managedby=aks
Annotations:      cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: tmp-dir
```
tigera-operator    tigera-operator    {"hostPath":{"path":"/var/lib/calico","type":""},"name":"var-lib-calico"} 🆗
```bash
Pod Template:
Labels:           k8s-app=tigera-operator
kubernetes.azure.com/managedby=aks
name=tigera-operator
Annotations: …
```

Added annotations

---

CHANGELOG.md
bin/images/aws/imagenes-eks-distro.txt
pkg/cluster/internal/create/actions/createworker/aws.go
pkg/cluster/internal/create/actions/createworker/azure.go
pkg/cluster/internal/create/actions/createworker/createworker.go
pkg/cluster/internal/create/actions/createworker/gcp.go
pkg/cluster/internal/create/actions/createworker/keosinstaller.go
pkg/cluster/internal/create/actions/createworker/provider.go
pkg/commons/utils.go

Improve retries & remove golang warnings
- Improve execution commands retries.
- Remove golang warnings.
- Clean error output
- Increase get cluster timeout
- Refactor wait for calico namespace
Compile a binary with this branch and create a cluster in any provider.
- Cherry pick from [PR514](https://github.com/Stratio/kind/pull/514)

Improve retrys & remove golang warnings

---

CHANGELOG.md
pkg/cluster/internal/create/actions/createworker/createworker.go

Ensure CoreDNS replicas are assigned to different nodes
- https://stratio.atlassian.net/browse/CLOUD-45

[CLOUD-45] Asegurar replicas de coredns en distintos nodos

---

pkg/cluster/internal/providers/docker/stratio/Dockerfile

Al autoescalar un grupo de nodos, las instancias se crean y se agregan al cluster de K8s como nodos en Ready, pero no se refleja el cambio de replicas en el "spec.replicas" de lo "machinepools".
Solución propuesta:
Modificar los permisos necesarios en el ficher infrastructure-components.yaml que nos descargamos del provider para poder añadir los permisos necesarios en el role del capg-manager, con objetivo de poder modificar los machinepools.
- PR: https://github.com/Stratio/cluster-api-provider-gcp/pull/8
- Revisión del fichero infrastructure-components.yaml (avoid-creation)
- Revisión de los permisos añadidos en el role en el workload cluster
[PLT-99]: https://stratio.atlassian.net/browse/PLT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PLT-563] Modify Dockerfile to add permissions on capg-manager role

---

pkg/cluster/internal/create/actions/createworker/provider.go

fix keoscluster-registries creation workload cluster
```bash
2024-09-24T15:14:45Z    ERROR   could not get docker registries credentials: secrets "keoscluster-registries" not found {"controller": "keoscluster", "controllerGroup": "installer.stratio.com", "controllerKind": "
KeosCluster", "KeosCluster": {"name":"janr-aws","namespace":"cluster-janr-aws"}, "namespace": "cluster-janr-aws", "name": "janr-aws", "reconcileID": "4e185766-01b2-4ecd-9ca0-44b1b4d15a58", "error": "could not get
docker registries credentials: secrets \"keoscluster-registries\" not found"}
```
N/A

[FIX][0.6] Fix keoscluster-registries creation workload cluster

---

pkg/cluster/internal/create/actions/createworker/createworker.go
pkg/cluster/internal/create/actions/createworker/gcp.go
pkg/cluster/internal/create/actions/createworker/provider.go
pkg/cluster/internal/providers/docker/stratio/Dockerfile
pkg/commons/cluster.go

Hasta este momento se instalaba en clusters gestionados de EKS y GKE calico como motor de políticas de red de forma manual, mediante un chart de helm y delegando la parte de CNI al propio addon del cloud provider. Se comprobó que esta forma de instalación no funcionaba para GKE y en caso de querer utilizar calico como motor de politicas de red debía ser instalado como addon de GKE.
Se ha eliminado la comprobación que permitía la instalación en GKE del chart de tigera-operator y se ha añadido a la sección de la networkPolicy del template de GKE
https://github.com/Stratio/cluster-operator/pull/232

[PLT-929] Removed calico installation as policy manager by helm chart in GKE

---

CHANGELOG.md
pkg/cluster/internal/validate/gcp.go
pkg/commons/cluster.go

Soporte CMEK:
Ejemplo:
worker_nodes:
root_volume:
encrypted: true
size: 50
type: pd-standard
encryption_key: "projects/PROJECT_ID/locations/LOCATION/keyRings/KEY_RING/cryptoKeys/KEY_NAME"
Soporte SA:
Ejemplo:
spec:
security:
nodes_identity: "<sa_name>@<PROJECT_ID>.iam.gserviceaccount.com"
Soporte CIDR's:
Ejemplo:
control_plane:
managed: true
gcp:
ip_allocation_policy:
cluster_secondary_range_name: "gkepods-europe-west4"
services_secondary_range_name: "gkeservices-europe-west4"
Ejemplo:
control_plane:
managed: true
gcp:
ip_allocation_policy:
cluster_ipv4_cidr_block: 10.180.0.0/14
services_ipv4_cidr_block: 10.8.32.0/20
cluster-operator: https://github.com/Stratio/cluster-operator/pull/247
cluster-api-provider-gcp: https://github.com/Stratio/cluster-api-provider-gcp/pull/36
JIRA: …

[PLT-1330] CMEK, SA & CIDRs

---

CHANGELOG.md
scripts/upgrade-provisioner.py

Para validarlo de forma unitaria se ha hecho lo siguiente:
- Crear el `ClusterRole` `aws-node` con la siguiente definición:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: aws-node
rules:
- apiGroups:
- crd.k8s.amazonaws.com
resources:
- eniconfigs
verbs:
- list
- watch
- get
- apiGroups:
- ""
resources:
- namespaces
verbs:
- list
- watch
- get
- apiGroups:
- ""
resources:
- pods
verbs:
- list
- watch
- get
- apiGroups:
- ""
resources:
- nodes
verbs:
- list
- watch
- get
- update
- apiGroups:
- extensions
resources:
- '*'
verbs:
- list
- watch
- apiGroups:
- ""
- events.k8s.io
resources:
- events
verbs:
- create
- patch
- list
```
- Ejecutar el siguiente script para replicar el caso de uso de las modificaciones en el recurso `ClusterRole` `aws-node`: …

[PLT-1654] Fix AWS ClusterRole patch during cloud-provisioner upgrade

---

CHANGELOG.md
DEPENDENCIES
bin/images/aws/imagenes-capa.txt
bin/images/commons/imagenes-capi.txt
bin/images/gcp/imagenes-coredns.txt
pkg/cluster/internal/create/actions/createworker/createworker.go
pkg/cluster/internal/create/actions/createworker/provider.go
pkg/cluster/internal/create/actions/createworker/templates/gcp/28/coredns_deployment.tmpl
pkg/cluster/internal/create/actions/createworker/templates/gcp/29/coredns_deployment.tmpl
pkg/cluster/internal/create/actions/createworker/templates/gcp/30/coredns_deployment.tmpl
pkg/cluster/internal/providers/docker/stratio/Dockerfile
pkg/cluster/internal/providers/docker/stratio/upgrade/Dockerfile
stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc

[PLT-1628] Fix coredns, cluster-api-gcp and kube-rbac-proxy image registry and repository references

---

stratio-docs/en/antora.yml
stratio-docs/es/antora.yml

Esta PR actualiza la versión de documentación recogida en el fichero antora.yml, que por error indica la 0.5 cuando debe ser la 0.6.

[branch-0.17.0-0.6] antora.yml version update to 0.6

---

pkg/cluster/internal/create/actions/createworker/createworker.go
pkg/cluster/internal/providers/docker/stratio/Dockerfile

- Añadimos el clid e aws al Dockerfile para poder obtener las subnetes con ciertos tags
- Añadimos las eniconfig que el provider no genera para que el vpc-cni (aws-node) puede funcionar correctamente
N/A

[PLT-1716] [EKS] Desplegar utilizando únicamente el parámetro pods_cir en networks falla

---

CHANGELOG.md
DEPENDENCIES
docs/images/commons/imagenes-cluster-autoscaler.txt
pkg/cluster/internal/create/actions/createworker/aws.go
pkg/cluster/internal/create/actions/createworker/azure.go
pkg/cluster/internal/create/actions/createworker/templates/common/32/cluster-autoscaler-helm-values.tmpl
stratio-docs/en/modules/operations-manual/pages/offline-installation/common-images.adoc
stratio-docs/es/modules/operations-manual/pages/offline-installation/common-images.adoc

[PLT-2653] Bump cluster-autoscaler version to v1.33.0
https://github.com/Stratio/kubernetes-universe/pull/3015
[PLT-2653]: https://stratio.atlassian.net/browse/PLT-2653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PLT-2653] Bump cluster-autoscaler version to v1.33.0

---

CHANGELOG.md
DEPENDENCIES

Bump addon versions
https://github.com/Stratio/cluster-operator/pull/296

[PLT-2723] Bump aws-ebs-csi-driver, coredns, kube-proxy and vpc-cni addons versions

---

CHANGELOG.md
DEPENDENCIES
docs/images/gcp/imagenes-coredns.txt
pkg/cluster/internal/create/actions/createworker/templates/gcp/32/coredns_deployment.tmpl
stratio-docs/en/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc
stratio-docs/es/modules/operations-manual/pages/offline-installation/gcp-gke-images.adoc

Bump CoreDNS version from v1.9.4 to v1.12.4
https://github.com/Stratio/kubernetes-universe/pull/3058

[PLT-2629] Bump CoreDNS to version v1.12.4
